scalar DateTime

type Marcacion {
    id: ID!
    usuario: Usuario
    tipo: TipoMarcacion
    
    latitud: Float
    longitud: Float
    precisionGps: Float
    distanciaSucursalMetros: Int
    
    deviceId: String
    deviceInfo: String
    
    sucursalEntrada: Sucursal
    fechaEntrada: String
    
    sucursalSalida: Sucursal
    fechaSalida: String
    
    autorizacion: Int
    codigo: String
}

input MarcacionInput {
    id: ID
    usuarioId: ID
    tipo: TipoMarcacion
    
    latitud: Float
    longitud: Float
    precisionGps: Float
    distanciaSucursalMetros: Int
    
    deviceId: String
    deviceInfo: String
    
    sucursalEntradaId: ID
    fechaEntrada: String
    
    sucursalSalidaId: ID
    fechaSalida: String
    
    codigo: String
    embedding: [Float]
}

enum TipoMarcacion {
    ENTRADA
    SALIDA
}

extend type Query {
    marcacion(id: ID!): Marcacion
    marcacionesPorUsuario(usuarioId: ID!, fechaInicio: String, fechaFin: String, page: Int, size: Int): [Marcacion]
    marcaciones(page: Int, size: Int): [Marcacion]
    imprimirReporteMarcaciones(usuarioId: ID, fechaInicio: String, fechaFin: String, usuarioResponsableId: ID): String
}

extend type Mutation {
    saveMarcacion(marcacion: MarcacionInput!): Marcacion
}
