type Modelo {
    id:ID!
    descripcion: String
    marca: Marca
    creadoEn: Date
    usuario: Usuario
}

input ModeloInput {
    id:ID
    descripcion: String
    marcaId: Int
    usuarioId: Int
}

type ModeloPage {
    getTotalPages: Int
    getTotalElements: Int
    getNumberOfElements: Int
    isFirst: Boolean
    isLast: Boolean
    hasNext: Boolean
    hasPrevious: Boolean
    getContent: [Modelo]
    getPageable: Pageable
}

extend type Query {
    modelo(id:ID!):Modelo
    modelos(page:Int = 0, size:Int = 10):[Modelo]!
    countModelo: Int
    modeloSearchPage(texto: String, page: Int, size: Int): ModeloPage
    modelosByMarca(marcaId:ID!, texto:String, page:Int = 0, size:Int = 10):[Modelo]
}

extend type Mutation {
    saveModelo(modelo:ModeloInput!):Modelo!
    deleteModelo(id:ID!):Boolean!
}

