input PeriodoGraficoInput {
    etiqueta: String!
    inicio: String!
    fin: String!
}

type DesglosePeriodoGrafico {
    etiqueta: String!
    total: Float!
    cantidad: Float
}

type DesgloseAnhoGrafico {
    anio: Int!
    total: Float!
    cantidad: Float
}

type IngresoGastoSerieGrafico {
    anio: Int!
    sucId: ID
    sucursalNombre: String
    ingresos: [VentaPorMes!]!
    gastos: [GastoPorMes!]!
}

type VentasPorHoraSerieGrafico {
    sucId: ID
    sucursalNombre: String
    etiqueta: String!
    fecha: String!
    datos: [VentaPorHora!]!
}

type VentaPorCiudad {
    ciudadId: ID
    nombre: String
    total: Float
    desglosePeriodos: [DesglosePeriodoGrafico!]
    desgloseAnhos: [DesgloseAnhoGrafico!]
}

extend type Query {
    ventasPorFuncionarioMulti(
        periodos: [PeriodoGraficoInput!]!
        sucIds: [ID]
        usuarioIds: [ID]
    ): [VentaPorFuncionario!]!

    formaPagoEstadisticasMulti(
        periodos: [PeriodoGraficoInput!]!
        sucIds: [ID]
    ): [FormaPagoEstadistica!]!

    gastosPorCategoriaMulti(
        periodos: [PeriodoGraficoInput!]!
        sucIds: [ID]
    ): [GastoPorCategoria!]!

    ventasPorSucursalMulti(
        periodos: [PeriodoGraficoInput!]!
    ): [VentaPorSucursal!]!

    ventasPorCiudadMulti(
        periodos: [PeriodoGraficoInput!]!
    ): [VentaPorCiudad!]!

    productosMasVendidosMulti(
        periodos: [PeriodoGraficoInput!]!
        sucIds: [ID]
        limit: Int
        familiaId: ID
        ascendente: Boolean
        productoIds: [ID]
    ): [ProductoVendidoEstadistica!]!

    ingresosGastosPorMesMulti(
        anios: [Int!]!
        sucIds: [ID]
    ): [IngresoGastoSerieGrafico!]!

    ventasPorHoraMulti(
        periodos: [PeriodoGraficoInput!]!
        sucIds: [ID]
    ): [VentasPorHoraSerieGrafico!]!
}
