type HojaRuta {
    id: ID!
    vehiculo: Vehiculo
    chofer: Persona
    fechaSalida: Date
    fechaLlegada: Date
    kmSalida: Float
    kmLlegada: Float
    estado: String
    creadoEn: Date
    acompanantes: [Persona]
}

input HojaRutaInput {
    id: ID
    vehiculoId: Int
    choferId: Int
    fechaSalida: Date
    fechaLlegada: Date
    kmSalida: Float
    kmLlegada: Float
    estado: String
    acompanantesIds: [Int]
}

extend type Query {
    hojaRuta(id: ID!): HojaRuta
    hojaRutaList(page: Int = 0, size: Int = 10): [HojaRuta]!
    hojaRutaPorVehiculo(vehiculoId: ID!, page: Int = 0, size: Int = 10): [HojaRuta]
    hojaRutaPorChofer(choferId: ID!, page: Int = 0, size: Int = 10): [HojaRuta]
    hojaRutaActivaPorVehiculo(vehiculoId: ID!): HojaRuta
    choferesConEntregas(page: Int = 0, size: Int = 20): [Persona]!
    transferenciasPorChofer(choferId: ID!, page: Int = 0, size: Int = 20): [Transferencia]!
}

extend type Mutation {
    saveHojaRuta(input: HojaRutaInput!): HojaRuta!
    deleteHojaRuta(id: ID!): Boolean!
}
