type MovimientoStock {
    id:ID!
    producto: Producto
    tipoMovimiento: TipoMovimiento
    referencia: Int
    creadoEn: Date
    usuario: Usuario
    cantidad: Float
    estado: Boolean
    proveedor: Proveedor
    sucursalId: ID
    sucursal: Sucursal
}

input MovimientoStockInput {
    id:ID
    productoId: ID
    tipoMovimiento: TipoMovimiento
    referencia: Int
    usuarioId: ID
    cantidad: Float
    estado: Boolean
    sucursalId: ID
}

type MovimientoStockPage {
    getTotalPages: Int
    getTotalElements: Int
    getNumberOfElements: Int
    isFirst: Boolean
    isLast: Boolean
    hasNext: Boolean
    hasPrevious: Boolean
    getContent: [MovimientoStock]
    getPageable: Pageable
}

type ResumenMovimientoStock {
    cantidadMovimientos: Int
    stock: Float
}

type StockPorTipoMovimientoDto {
    tipoMovimiento: TipoMovimiento
    stock: Float
}

type ProductoSaldoDto {
    productoId: ID!
    productoDescripcion: String
    sucursalId: ID!
    saldoTotal: Float
    imagenPrincipal: String
}

type ProductoSaldoPage {
    getTotalPages: Int
    getTotalElements: Int
    getNumberOfElements: Int
    isFirst: Boolean
    isLast: Boolean
    hasNext: Boolean
    hasPrevious: Boolean
    getContent: [ProductoSaldoDto]
    getPageable: Pageable
}

extend type Query {
    movimientoStock(id:ID!, sucId: ID):MovimientoStock
    movimientosStock(page:Int = 0, size:Int = 10, sucId: ID):[MovimientoStock]!
    countMovimientoStock: Int
    movimientoStockByFecha(inicio: String, fin: String, sucId: ID):[MovimientoStock]
    stockPorProducto(id:ID!, sucId: ID):Float
    stockByProductoIdExeptMovimientoId(productoId: ID!, movimientoId: ID!, sucursalId: ID!): Float
    stockByProductoIdAntesDeFecha(productoId: ID!, sucursalId: ID!, fecha: String!): Float
    findMovimientoStockByFilters(inicio: String, fin: String, sucursalList: [ID], productoId: ID,tipoMovimientoList: [TipoMovimiento],usuarioId: ID, page: Int, size: Int): MovimientoStockPage
    findStockWithFilters(inicio: String, fin: String, sucursalList: [ID], productoId: ID,tipoMovimientoList: [TipoMovimiento],usuarioId: ID): Float
    findStockPorTipoMovimiento(inicio: String, fin: String, sucursalList: [ID], productoId: ID,tipoMovimientoList: [TipoMovimiento],usuarioId: ID): [StockPorTipoMovimientoDto]
    productosConCantidadPositiva(sucursalId: ID, productoId: ID, page: Int = 0, size: Int = 10): ProductoSaldoPage
    productosConCantidadNegativa(sucursalId: ID, productoId: ID, page: Int = 0, size: Int = 10): ProductoSaldoPage
    productosFaltantes(sucursalId: ID!, productoId: ID, fechaInicio: String!, fechaFin: String!, page: Int = 0, size: Int = 10): ProductoSaldoPage
}

extend type Mutation {
    saveMovimientoStock(movimientoStock:MovimientoStockInput!):MovimientoStock!
    deleteMovimientoStock(id:ID!, sucId: ID):Boolean!
}

enum TipoMovimiento {
    COMPRA, VENTA, DEVOLUCION, DESCARTE, AJUSTE, TRANSFERENCIA, CALCULO, ENTRADA, SALIDA
}