type NotaRecepcion {
    id: ID!
    pedido: Pedido
    compra: Compra
    documento: Documento
    numero: Int
    tipoBoleta: String
    timbrado: Int
    fecha: Date
    moneda: Moneda!
    cotizacion: Float
    estado: NotaRecepcionEstado!
    pagado: Boolean
    creadoEn: Date
    usuario: Usuario
}

input NotaRecepcionInput {
    id: ID
    pedidoId: Int
    compraId: Int
    documentoId: Int
    numero: Int
    tipoBoleta: String
    timbrado: Int
    fecha: String
    monedaId: Int!
    cotizacion: Float
    estado: NotaRecepcionEstado!
    pagado: Boolean
    creadoEn: String
    usuarioId: Int
}

type NotaRecepcionPage {
    getTotalPages: Int
    getTotalElements: Int
    getNumberOfElements: Int
    isFirst: Boolean
    isLast: Boolean
    hasNext: Boolean
    hasPrevious: Boolean
    getContent: [NotaRecepcion]
    getPageable: Pageable
}

extend type Query {
    notaRecepcion(id: ID!): NotaRecepcion
    notaRecepcions(page: Int = 0, size: Int = 10): [NotaRecepcion]!
    countNotaRecepcion: Int
    notaRecepcionPorPedidoId(id: ID!): [NotaRecepcion]
    notaRecepcionPorPedidoIdAndNumero(id: ID!, numero: Int, page: Int, size: Int): NotaRecepcionPage
    countNotaRecepcionPorPedidoId(id: ID!): Int
    findByProveedorAndNumero(id: ID!, numero: Int!): [NotaRecepcion]
    findByNumero(numero: Int!): [NotaRecepcion]
    findNotasDisponiblesParaRecepcion(numero: Int, proveedorId: ID, sucursalId: ID): [NotaRecepcion]
}

extend type Mutation {
    saveNotaRecepcion(entity: NotaRecepcionInput!): NotaRecepcion!
    deleteNotaRecepcion(id: ID!): Boolean!
}

enum NotaRecepcionEstado {
    PENDIENTE_CONCILIACION
    CONCILIADA
    EN_RECEPCION
    RECEPCION_PARCIAL
    RECEPCION_COMPLETA
    CERRADA
}


