type PedidoItem {
    id:ID!
    pedido: Pedido
    producto: Producto
    presentacionCreacion: Presentacion
    cantidadSolicitada: Float
    precioUnitarioSolicitado: Float
    vencimientoEsperado: Date
    observacion: String
    esBonificacion: Boolean
    estado: PedidoItemEstado
    creadoEn: Date
    usuarioCreacion: Usuario
    distribucionConcluida: Boolean
    cantidadPendiente: Float
}

input PedidoItemInput {
    id:ID
    pedidoId: Int
    productoId: Int
    presentacionCreacionId: Int
    cantidadSolicitada: Float
    precioUnitarioSolicitado: Float
    vencimientoEsperado: String
    observacion: String
    esBonificacion: Boolean
    estado: PedidoItemEstado
    creadoEn: Date
    usuarioCreacionId: Int
}

type PedidoItemPage {
    getTotalPages: Int
    getTotalElements: Int
    getNumberOfElements: Int
    isFirst: Boolean
    isLast: Boolean
    hasNext: Boolean
    hasPrevious: Boolean
    getContent: [PedidoItem]
    getPageable: Pageable
}

extend type Query {
    pedidoItem(id:ID!):PedidoItem
    pedidoItemPorPedidoPage(id:ID!, page:Int = 0, size:Int = 10, texto: String, soloPendientes: Boolean):PedidoItemPage!
    pedidoItemPorPedido(id:ID!):[PedidoItem]!
    countPedidoItem: Int
    cantidadItensFaltaVerificarNota(id:ID!):Int
    cantidadItensFaltaVerificarProducto(id:ID!):Int
    # findHistoricoCompras(productoId: ID!, page: Int!, size: Int!): PedidoItemPage!
}

extend type Mutation {
    savePedidoItem(pedidoItem:PedidoItemInput!):PedidoItem!
    deletePedidoItem(id:ID!):Boolean!
    updateNotaRecepcion(pedidoItemId: ID!, notaRecepcionId: ID): PedidoItem
    addPedidoItemToNotaRecepcion(notaRecepcion: ID, pedidoItemId: ID!): PedidoItem
    verificarRecepcionProducto(pedidoItemId: ID!, verificar: Boolean!):PedidoItem
}

enum PedidoItemEstado {
    ACTIVO,
    CANCELADO,
    DEVOLUCION,
    CONCLUIDO,
    EN_FALTA
}


