type PedidoItemSucursal {
    id:ID!
    pedidoItem: PedidoItem
    sucursal: Sucursal
    sucursalEntrega: Sucursal
    cantidadPorUnidad: Float
    cantidadPorUnidadRecibida: Float
    stockDisponible: Float
    creadoEn: Date
    usuario: Usuario
    
}

input PedidoItemSucursalInput {
    id:ID
    pedidoItemId: Int
    sucursalId: Int
    sucursalEntregaId: Int
    cantidadPorUnidad: Float
    cantidadPorUnidadRecibida: Float
    usuarioId: Int
}

extend type Query {
    pedidoItemSucursal(id:ID!):PedidoItemSucursal
    pedidoItensSucursal(page:Int = 0, size:Int = 10):[PedidoItemSucursal]!
    countPedidoItemSucursal: Int
    pedidoItemSucursalPorPedidoItem(id: Int!):[PedidoItemSucursal]!
}

extend type Mutation {
    savePedidoItemSucursal(entity:PedidoItemSucursalInput!):PedidoItemSucursal!
    deletePedidoItemSucursal(id:ID!):Boolean!
}



