type RecepcionMercaderiaItem {
    id: ID
    recepcionMercaderia: RecepcionMercaderia
    notaRecepcionItem: NotaRecepcionItem
    producto: Producto
    presentacionRecibida: Presentacion
    sucursalEntrega: Sucursal
    cantidadRecibida: Float
    cantidadRechazada: Float
    vencimientoRecibido: Date
    lote: String
    esBonificacion: Boolean
    motivoRechazo: String
    observaciones: String
}

input RecepcionMercaderiaItemInput {
    id: ID
    recepcionMercaderiaId: Int
    notaRecepcionItemId: Int
    productoId: Int
    presentacionRecibidaId: Int
    sucursalEntregaId: Int
    cantidadRecibida: Float
    cantidadRechazada: Float
    vencimientoRecibido: String
    lote: String
    esBonificacion: Boolean
    motivoRechazo: String
    observacion: String
    creadoEn: String
}

extend type Query {
    recepcionMercaderiaItem(id: ID!): RecepcionMercaderiaItem
    recepcionMercaderiaItemsPorRecepcion(recepcionId: ID!): [RecepcionMercaderiaItem]
    recepcionMercaderiaItemsPorProductoYSucursal(productoId: ID!, sucursalId: ID!): [RecepcionMercaderiaItem]
}

extend type Mutation {
    saveRecepcionMercaderiaItem(entity: RecepcionMercaderiaItemInput!): RecepcionMercaderiaItem!
} 