type Sucursal {
    id:ID!
    nombre: String
    localizacion: String
    ciudad: Ciudad
    deposito: Boolean
    depositoPredeterminado: Boolean
    creadoEn: Date
    usuario: Usuario
    direccion: String
    nroDelivery: String
    isConfigured: Boolean
    sectorList: [Sector]
    codigoEstablecimientoFactura: String
    activo: Boolean
    ip: String
    puerto: Int
}

input SucursalInput {
    id:ID
    nombre: String
    localizacion: String
    ciudadId: Int
    deposito: Boolean
    depositoPredeterminado: Boolean
    usuarioId: Int
    direccion: String
    nroDelivery: String
    isConfigured: Boolean
    activo: Boolean
    codigoEstablecimientoFactura: String
    creadoEn: String
    ip: String
    puerto: Int
}

type SucursalPage {
    getTotalPages: Int
    getTotalElements: Int
    getNumberOfElements: Int
    isFirst: Boolean
    isLast: Boolean
    hasNext: Boolean
    hasPrevious: Boolean
    getContent: [Sucursal]
    getPageable: Pageable
}

extend type Query {
    sucursal(id:ID!):Sucursal
    sucursales(page:Int = 0, size:Int = 10):[Sucursal]!
    countSucursal: Int
    sucursalesSearch(texto:String, activo:Boolean):[Sucursal]
    sucursalActual:Sucursal
    findByNombre(nombre: String, page: Int, size: Int): SucursalPage
}

extend type Mutation {

    saveSucursal(sucursal:SucursalInput!):Sucursal!
    deleteSucursal(id:ID!):Boolean!
}

