spring.datasource.url=jdbc:postgresql://localhost:5551/bodega_fact_test_2

# Esto puede ser:
# DEV (apunta al ambiente de desarrollo/test de SIFEN)
# PROD (apunta al ambiente de producción de SIFEN)
sifen.ambiente=PROD

# NO modificar a menos que uno sepa bien lo que está haciendo
# sifen.url_base=

# Si se va a usar el certificado cliente.
# Este valor en el 99.99% de las veces va a ser true
# a menos que uno sepa bien lo que está haciendo
sifen.certificado.usar=true
# Por ahora, el único valor aceptado es PFX
sifen.certificado.tipo=PFX

## RUTA APUNTANDO AL ARCHIVO PFX
sifen.certificado.archivo=/Users/gabfranck/workspace/frc-sistemas-informaticos/backend/central/frc-central-server/src/main/resources/certificados/certificado.pfx

## PASSWORD del ARCHIVO PFX
sifen.certificado.contrasena=fasa1701

## Nota técnica 13 (23/04/2023)
## Para habilitar los campos nuevos de esta nota técnica, cambiar a true
sifen.habilitar-nota-tecnica-13=true

## CSC
sifen.csc=D37561586c1CAd69A2e7747E73f9F03B
sifen.csc-id=0001
tipoContribuyenteEmisor=2