enum ConfiguracionRrhhTipo {
    NUMBER
    STRING
    BOOLEAN
    DATE
}

type ConfiguracionRrhh {
    id: ID!
    clave: String
    valor: String
    tipo: ConfiguracionRrhhTipo
    descripcion: String
    activo: Boolean
    usuario: Usuario
    creadoEn: Date
}

input ConfiguracionRrhhInput {
    id: ID
    clave: String
    valor: String
    tipo: ConfiguracionRrhhTipo
    descripcion: String
    activo: Boolean
    creadoEn: Date
    usuarioId: Int
}

type LiquidacionConcepto {
    id: ID!
    codigo: String
    descripcion: String
    esHaber: Boolean
    esCalculadoAuto: Boolean
    activo: Boolean
    usuario: Usuario
    creadoEn: Date
}

input LiquidacionConceptoInput {
    id: ID
    codigo: String
    descripcion: String
    esHaber: Boolean
    esCalculadoAuto: Boolean
    activo: Boolean
    creadoEn: Date
    usuarioId: Int
}

extend type Query {
    configuracionRrhh(id: ID!): ConfiguracionRrhh
    configuracionRrhhPorClave(clave: String!): ConfiguracionRrhh
    configuracionesRrhh(page: Int = 0, size: Int = 50): [ConfiguracionRrhh]!
    configuracionesRrhhSearch(texto: String): [ConfiguracionRrhh]
    countConfiguracionRrhh: Int
    liquidacionConcepto(id: ID!): LiquidacionConcepto
    liquidacionConceptoPorCodigo(codigo: String!): LiquidacionConcepto
    liquidacionConceptos(page: Int = 0, size: Int = 50): [LiquidacionConcepto]!
    countLiquidacionConcepto: Int
}

extend type Mutation {
    saveConfiguracionRrhh(configuracionRrhh: ConfiguracionRrhhInput!): ConfiguracionRrhh!
    deleteConfiguracionRrhh(id: ID!): Boolean!
    saveLiquidacionConcepto(liquidacionConcepto: LiquidacionConceptoInput!): LiquidacionConcepto!
    deleteLiquidacionConcepto(id: ID!): Boolean!
}
