type CajaVirtualConfiguracion {
    id: ID!
    cajaVirtual: CajaVirtual
    mostrarCuentasPorPagar: Boolean
    mostrarCuentasPorCobrar: Boolean
    operacionesFinancierasHabilitado: Boolean
    formasPagoVisibles: [FormaPago]
    cuentasBancariasVisibles: [CuentaBancaria]
    cuentasBancariasOrden: String
    creadoEn: Date
}

input CajaVirtualConfiguracionInput {
    cajaVirtualId: Int!
    mostrarCuentasPorPagar: Boolean
    mostrarCuentasPorCobrar: Boolean
    operacionesFinancierasHabilitado: Boolean
    formasPagoVisiblesIds: [Int]
    cuentasBancariasVisiblesIds: [Int]
    cuentasBancariasOrden: String
}

extend type Query {
    cajaVirtualConfiguracion(cajaVirtualId: ID!): CajaVirtualConfiguracion
}

extend type Mutation {
    saveCajaVirtualConfiguracion(input: CajaVirtualConfiguracionInput!): CajaVirtualConfiguracion!
}
