type Vehiculo {
    id:ID!
    modelo: Modelo
    tipoVehiculo: TipoVehiculo
    chapa: String
    color: String
    anho: Int
    documentacion: Boolean
    refrigerado: Boolean
    nuevo: Boolean
    fechaAdquisicion: Date
    primerKilometraje: Float
    capacidadKg: Float
    capacidadPasajeros: Int
    imagenesVehiculo: String
    imagenesDocumentos: String
    creadoEn: Date
    usuario: Usuario
}

input VehiculoInput {
    id:ID
    modeloId: Int
    tipoVehiculoId: Int
    chapa: String
    color: String
    anho: Int
    documentacion: Boolean
    refrigerado: Boolean
    nuevo: Boolean
    fechaAdquisicion: String
    primerKilometraje: Float
    capacidadKg: Float
    capacidadPasajeros: Int
    imagenesVehiculo: String
    imagenesDocumentos: String
    usuarioId: Int
}

extend type Query {
    vehiculo(id:ID!):Vehiculo
    vehiculos(page:Int = 0, size:Int = 10):[Vehiculo]!
    countVehiculo: Int
    vehiculoSearch(texto:String):[Vehiculo]
    vehiculoSearchWithPage(texto:String, page:Int = 0, size:Int = 10):[Vehiculo]
    vehiculoByChapa(chapa:String):Vehiculo
    vehiculosByMarca(marcaId:ID!):[Vehiculo]
    vehiculosByModelo(modeloId:ID!):[Vehiculo]
    vehiculosByTipoVehiculo(tipoVehiculoId:ID!):[Vehiculo]
}

extend type Mutation {
    saveVehiculo(vehiculo:VehiculoInput!):Vehiculo!
    deleteVehiculo(id:ID!):Boolean!
}

