type VehiculoSucursal {
    id:ID!
    vehiculo: Vehiculo
    sucursal: Sucursal
    responsable: Funcionario
    creadoEn: Date
    usuario: Usuario
}

input VehiculoSucursalInput {
    id:ID
    vehiculoId: Int
    sucursalId: Int
    responsableId: Int
    usuarioId: Int
}

extend type Query {
    vehiculoSucursal(id:ID!):VehiculoSucursal
    vehiculosSucursal(page:Int = 0, size:Int = 10):[VehiculoSucursal]!
    countVehiculoSucursal: Int
    vehiculosSucursalByVehiculo(vehiculoId:ID!):[VehiculoSucursal]
    vehiculosSucursalBySucursal(sucursalId:ID!):[VehiculoSucursal]
}

extend type Mutation {
    saveVehiculoSucursal(vehiculoSucursal:VehiculoSucursalInput!):VehiculoSucursal!
    deleteVehiculoSucursal(id:ID!):Boolean!
}

