package com.franco.dev.domain.operaciones.enums;

public enum EtapaTransferencia {
    PRE_TRANSFERENCIA_CREACION,
    PRE_TRANSFERENCIA_ORIGEN,
    PREPARACION_MERCADERIA,
    PREPARACION_MERCADERIA_CONCLUIDA,
    TRANSPORTE_VERIFICACION,
    TRANSPORTE_EN_CAMINO,
    TRANSPORTE_EN_DESTINO,
    RECEPCION_EN_VERIFICACION,
    RECEPCION_CONCLUIDA
}
