package com.franco.dev.domain.operaciones.enums;

public enum TipoSalida {

    SUCURSAL, // LA SALIDA PROVIENE DE UNA TRANSFERENCIA DE SUCURSAL
    VENCIDO, // LA SALIDA DE PRODUCTOS VENCIDOS
    DETERIORADO, // LA SALIDA DE PRODUCTOS DETERIORADOS
    AJUSTE, // LA ENTRADA ES UN AJUSTE DE STOCK

}
