package com.franco.dev.rabbit.enums;

public enum TipoAccion {
    GUARDAR,
    ACTUALIZAR,
    DELETE,
    SOLICITAR_DB,
    VERIFICAR,
    SOLICITAR_SUCURSALES,
    SOLICITAR_ENTIDAD,
    SOLICITAR_STOCK_PRODUCTO,
    FINALIZAR_INVENTARIO,
    GUARDAR_IMAGEN,
    GUARDAR_ARCHIVO,
    SOLICITAR_CAJA_ABIERTA,
    SOLICITAR_MALETIN
}
