-- Sync configuraciones.replication_table with tables currently in pg_publication_tables.
-- Inserts any table that appears in publications but is not yet registered in replication_table.
-- Direction MAIN_TO_ALL = central to branches; BRANCH_TO_MAIN = branch to central.

INSERT INTO configuraciones.replication_table (table_name, direction, description, creado_en)
VALUES
-- MAIN_TO_ALL (central → branches) - missing from initial seed
('empresarial.zona', 'MAIN_TO_ALL', 'Zona', NOW()),
('equipos.equipo', 'MAIN_TO_ALL', 'Equipo', NOW()),
('equipos.tipo_equipo', 'MAIN_TO_ALL', 'Tipo de equipo', NOW()),
('financiero.banco', 'MAIN_TO_ALL', 'Banco', NOW()),
('financiero.cambio', 'MAIN_TO_ALL', 'Cambio', NOW()),
('financiero.cuenta_bancaria', 'MAIN_TO_ALL', 'Cuenta bancaria', NOW()),
('financiero.documento', 'MAIN_TO_ALL', 'Documento', NOW()),
('financiero.forma_pago', 'MAIN_TO_ALL', 'Forma de pago', NOW()),
('financiero.moneda', 'MAIN_TO_ALL', 'Moneda', NOW()),
('financiero.moneda_billetes', 'MAIN_TO_ALL', 'Moneda billetes', NOW()),
('financiero.timbrado', 'MAIN_TO_ALL', 'Timbrado', NOW()),
('financiero.timbrado_detalle', 'MAIN_TO_ALL', 'Timbrado detalle', NOW()),
('financiero.tipo_gasto', 'MAIN_TO_ALL', 'Tipo de gasto', NOW()),
('general.barrio', 'MAIN_TO_ALL', 'Barrio', NOW()),
('general.ciudad', 'MAIN_TO_ALL', 'Ciudad', NOW()),
('general.contacto', 'MAIN_TO_ALL', 'Contacto', NOW()),
('general.pais', 'MAIN_TO_ALL', 'País', NOW()),
('operaciones.precio_delivery', 'MAIN_TO_ALL', 'Precio delivery', NOW()),
('personas.cliente', 'MAIN_TO_ALL', 'Cliente', NOW()),
('personas.funcionario', 'MAIN_TO_ALL', 'Funcionario', NOW()),
('personas.grupo_role', 'MAIN_TO_ALL', 'Grupo role', NOW()),
('personas.persona', 'MAIN_TO_ALL', 'Persona', NOW()),
('personas.role', 'MAIN_TO_ALL', 'Role', NOW()),
('personas.usuario', 'MAIN_TO_ALL', 'Usuario', NOW()),
('personas.usuario_grupo', 'MAIN_TO_ALL', 'Usuario grupo', NOW()),
('personas.usuario_role', 'MAIN_TO_ALL', 'Usuario role', NOW()),
('productos.codigo', 'MAIN_TO_ALL', 'Código', NOW()),
('productos.codigo_tipo_precio', 'MAIN_TO_ALL', 'Código tipo precio', NOW()),
('productos.costo_por_producto', 'MAIN_TO_ALL', 'Costo por producto', NOW()),
('productos.pdv_categoria', 'MAIN_TO_ALL', 'PDV categoría', NOW()),
('productos.pdv_grupo', 'MAIN_TO_ALL', 'PDV grupo', NOW()),
('productos.pdv_grupos_productos', 'MAIN_TO_ALL', 'PDV grupos productos', NOW()),
('productos.precio_por_sucursal', 'MAIN_TO_ALL', 'Precio por sucursal', NOW()),
('productos.presentacion', 'MAIN_TO_ALL', 'Presentación', NOW()),
('productos.producto_imagen', 'MAIN_TO_ALL', 'Producto imagen', NOW()),
('productos.producto_por_sucursal', 'MAIN_TO_ALL', 'Producto por sucursal', NOW()),
('productos.tipo_precio', 'MAIN_TO_ALL', 'Tipo precio', NOW()),
('productos.tipo_presentacion', 'MAIN_TO_ALL', 'Tipo presentación', NOW()),
('vehiculos.marca', 'MAIN_TO_ALL', 'Marca vehículo', NOW()),
('vehiculos.modelo', 'MAIN_TO_ALL', 'Modelo vehículo', NOW()),
('vehiculos.tipo_vehiculo', 'MAIN_TO_ALL', 'Tipo vehículo', NOW()),
('vehiculos.vehiculo', 'MAIN_TO_ALL', 'Vehículo', NOW()),
('vehiculos.vehiculo_sucursal', 'MAIN_TO_ALL', 'Vehículo sucursal', NOW()),
-- Documento electrónico (central → branch con filtro sucursal)
('financiero.documento_electronico', 'MAIN_TO_ALL', 'Documento electrónico', NOW()),
('financiero.evento_cancelacion_de', 'MAIN_TO_ALL', 'Evento cancelación DE', NOW()),
('financiero.evento_inutilizacion_de', 'MAIN_TO_ALL', 'Evento inutilización DE', NOW()),
('financiero.evento_inutilizacion_de_documento_electronico', 'MAIN_TO_ALL', 'Evento inutilización DE documento electrónico', NOW()),
('financiero.evento_nominacion_de', 'MAIN_TO_ALL', 'Evento nominación DE', NOW()),
('financiero.lote_de', 'MAIN_TO_ALL', 'Lote DE', NOW()),

-- BRANCH_TO_MAIN (branch → central) - missing from initial seed
('administrativo.marcacion', 'BRANCH_TO_MAIN', 'Marcación', NOW()),
('configuraciones.inicio_sesion', 'BRANCH_TO_MAIN', 'Inicio sesión', NOW()),
('financiero.cambio_caja', 'BRANCH_TO_MAIN', 'Cambio caja', NOW()),
('financiero.conteo', 'BRANCH_TO_MAIN', 'Conteo', NOW()),
('financiero.conteo_moneda', 'BRANCH_TO_MAIN', 'Conteo moneda', NOW()),
('financiero.gasto', 'BRANCH_TO_MAIN', 'Gasto', NOW()),
('financiero.gasto_detalle', 'BRANCH_TO_MAIN', 'Gasto detalle', NOW()),
('financiero.maletin', 'BRANCH_TO_MAIN', 'Maletín', NOW()),
('financiero.movimiento_caja', 'BRANCH_TO_MAIN', 'Movimiento caja', NOW()),
('financiero.movimiento_personas', 'BRANCH_TO_MAIN', 'Movimiento personas', NOW()),
('financiero.pdv_caja', 'BRANCH_TO_MAIN', 'PDV caja', NOW()),
('financiero.retiro', 'BRANCH_TO_MAIN', 'Retiro', NOW()),
('financiero.retiro_detalle', 'BRANCH_TO_MAIN', 'Retiro detalle', NOW()),
('financiero.sencillo', 'BRANCH_TO_MAIN', 'Sencillo', NOW()),
('financiero.sencillo_detalle', 'BRANCH_TO_MAIN', 'Sencillo detalle', NOW()),
('financiero.venta_credito', 'BRANCH_TO_MAIN', 'Venta crédito', NOW()),
('financiero.venta_credito_cuota', 'BRANCH_TO_MAIN', 'Venta crédito cuota', NOW()),
('operaciones.cobro', 'BRANCH_TO_MAIN', 'Cobro', NOW()),
('operaciones.cobro_detalle', 'BRANCH_TO_MAIN', 'Cobro detalle', NOW()),
('operaciones.delivery', 'BRANCH_TO_MAIN', 'Delivery', NOW()),
('operaciones.movimiento_stock', 'BRANCH_TO_MAIN', 'Movimiento stock', NOW()),
('operaciones.vuelto', 'BRANCH_TO_MAIN', 'Vuelto', NOW()),
('operaciones.vuelto_item', 'BRANCH_TO_MAIN', 'Vuelto item', NOW())
ON CONFLICT (table_name) DO NOTHING;
