-- Modulo Devoluciones: entidades de operacion (cabecera) para retiro a proveedor
-- y colecta interna. Aditiva. Da identidad y agrupacion estable a lo que antes
-- se agrupaba por atributos derivados.

CREATE TABLE IF NOT EXISTS operaciones.retiro_devolucion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           TIMESTAMP   NOT NULL,
    usuario_id      BIGINT,
    proveedor_id    BIGINT      NOT NULL,
    nro_comprobante VARCHAR(60),
    observacion     VARCHAR(255),
    estado          VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADO',
    creado_en       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operaciones.colecta_devolucion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha               TIMESTAMP   NOT NULL,
    usuario_id          BIGINT,
    sucursal_origen_id  BIGINT      NOT NULL,
    sucursal_destino_id BIGINT      NOT NULL,
    observacion         VARCHAR(255),
    estado              VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADO',
    creado_en           TIMESTAMP
);

ALTER TABLE operaciones.devolucion ADD COLUMN IF NOT EXISTS retiro_id  BIGINT;
ALTER TABLE operaciones.devolucion ADD COLUMN IF NOT EXISTS colecta_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_devolucion_retiro') THEN
        ALTER TABLE operaciones.devolucion
            ADD CONSTRAINT fk_devolucion_retiro FOREIGN KEY (retiro_id)
            REFERENCES operaciones.retiro_devolucion (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_devolucion_colecta') THEN
        ALTER TABLE operaciones.devolucion
            ADD CONSTRAINT fk_devolucion_colecta FOREIGN KEY (colecta_id)
            REFERENCES operaciones.colecta_devolucion (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_devolucion_retiro_id  ON operaciones.devolucion (retiro_id);
CREATE INDEX IF NOT EXISTS idx_devolucion_colecta_id ON operaciones.devolucion (colecta_id);
CREATE INDEX IF NOT EXISTS idx_retiro_dev_proveedor  ON operaciones.retiro_devolucion (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_colecta_dev_destino   ON operaciones.colecta_devolucion (sucursal_destino_id);
