-- Modulo Devoluciones: nota de credito consolidada por retiro a proveedor.
-- Aditiva. Reemplaza el registro per-devolucion (Devolucion.nro_nota_credito /
-- monto_acreditado) por una cabecera unica ligada a un retiro (1:1), con lineas
-- consolidadas por producto. saldo/estado quedan para uso futuro (aplicar el
-- credito a favor contra una compra).

CREATE TABLE IF NOT EXISTS operaciones.nota_credito_devolucion (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retiro_id        BIGINT       NOT NULL,
    proveedor_id     BIGINT       NOT NULL,
    nro_nota_credito VARCHAR(60),
    fecha            TIMESTAMP,
    monto_total      NUMERIC(18,4),
    saldo            NUMERIC(18,4),
    estado           VARCHAR(20)  NOT NULL DEFAULT 'DISPONIBLE',
    usuario_id       BIGINT,
    creado_en        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operaciones.nota_credito_devolucion_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_credito_id  BIGINT       NOT NULL,
    producto_id      BIGINT       NOT NULL,
    presentacion_id  BIGINT,
    cantidad         NUMERIC(18,4),
    costo_unitario   NUMERIC(18,4),
    cantidad_base    NUMERIC(18,4),
    total            NUMERIC(18,4)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_nota_credito_retiro') THEN
        ALTER TABLE operaciones.nota_credito_devolucion
            ADD CONSTRAINT uq_nota_credito_retiro UNIQUE (retiro_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_nota_credito_retiro') THEN
        ALTER TABLE operaciones.nota_credito_devolucion
            ADD CONSTRAINT fk_nota_credito_retiro FOREIGN KEY (retiro_id)
            REFERENCES operaciones.retiro_devolucion (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_nota_credito_item_nota') THEN
        ALTER TABLE operaciones.nota_credito_devolucion_item
            ADD CONSTRAINT fk_nota_credito_item_nota FOREIGN KEY (nota_credito_id)
            REFERENCES operaciones.nota_credito_devolucion (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_nota_credito_retiro    ON operaciones.nota_credito_devolucion (retiro_id);
CREATE INDEX IF NOT EXISTS idx_nota_credito_proveedor ON operaciones.nota_credito_devolucion (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_nc_item_nota           ON operaciones.nota_credito_devolucion_item (nota_credito_id);
