ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_pedido_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_pedido_fk FOREIGN KEY (pedido_id) REFERENCES operaciones.pedido(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_nota_recepcion_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_nota_recepcion_fk FOREIGN KEY (nota_recepcion_id) REFERENCES operaciones.nota_recepcion(id) ON DELETE SET NULL ON UPDATE SET NULL;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_autorizado_por_recepcion_nota_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_autorizado_por_recepcion_nota_fk FOREIGN KEY (autorizado_por_recepcion_nota_id) REFERENCES personas.usuario(id) ON UPDATE SET NULL;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_autorizado_por_recepcion_producto_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_autorizado_por_recepcion_producto_fk FOREIGN KEY (autorizado_por_recepcion_producto_id) REFERENCES personas.usuario(id) ON UPDATE SET NULL;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_presentacion_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_presentacion_fk FOREIGN KEY (presentacion_creacion_id) REFERENCES productos.presentacion(id) ON UPDATE RESTRICT;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_presentacion_recepcion_nota_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_presentacion_recepcion_nota_fk FOREIGN KEY (presentacion_recepcion_nota_id) REFERENCES productos.presentacion(id) ON UPDATE RESTRICT;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_presentacion_recepcion_producto_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_presentacion_recepcion_producto_fk FOREIGN KEY (presentacion_recepcion_producto_id) REFERENCES productos.presentacion(id) ON UPDATE RESTRICT;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_producto_id_fkey;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES productos.producto(id) ON UPDATE RESTRICT;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_usuario_recepcion_nota_id_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_usuario_recepcion_nota_id_fk FOREIGN KEY (usuario_recepcion_nota_id) REFERENCES personas.usuario(id) ON UPDATE SET NULL;
ALTER TABLE operaciones.pedido_item DROP CONSTRAINT pedido_item_usuario_recepcion_producto_id_recepcion_producto_fk;
ALTER TABLE operaciones.pedido_item ADD CONSTRAINT pedido_item_usuario_recepcion_producto_id_recepcion_producto_fk FOREIGN KEY (usuario_recepcion_producto_id) REFERENCES personas.usuario(id) ON UPDATE SET NULL;
