name: Deploy Auto

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy ${{ matrix.instance }}
    strategy:
      fail-fast: false
      matrix:
        instance: [alpha, farmacia, bodega]
    uses: ./.github/workflows/deploy.yml
    with:
      instance: ${{ matrix.instance }}
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
